
* 2016
** 2016-05 May
*** 2016-05-24 Tuesday
**** Journal - 24 May
     Dear Reader,

     It's been a while.  A long while.  I think I've started more
     journals to date than there were entries in any one journal.
     Let's see if we can't fix that.

     I'm almost to my graduation, for high school.  That's going to be
     super nice.  I'm so goddamn sick of attending Bishop Watterson.
     It's a waste of my time and my mental resources.

     I interview (and likely start) at Wallick next week.  Going to be
     nice to make >$10/hr and get significant experience in the field
     that'll likely support me through college.  

     Journaling is supposed to be about putting down a bunch of
     feelings, no?  I guess there's nowhere to put them but here, so
     here really goes.  I've been a fantastic muddle of feelings as of
     late.  There's the fact I no longer have to deal with high
     school, which means I can start studying the things I genuinely
     am interested in, and I've also gotten some important positions
     in things like the local Rocky Horror (I play Rocky himself next
     saturday and I'm a little nervous about it.  I can't do a
     clapping push-up, but I don't think it's that big a deal since
     the audience can't see me down there anyway.)  and the Open
     Source Club.  I ended this year on a series of the best notes
     possible, because not only are the things I just said true, but
     also I was the lead in our musical (a fantastic experience if
     ever there was such a thing), I got to, with the help of my close
     friends, hijack the closing night of traditions and say one last
     magnificent "fuck you" to Grace Beckman, and now I'm living as
     much of a dream as can be lived in Columbus while not actively
     fucking anyone.  I spend a month of this upcoming summer in
     France, and if all goes according to plan I'll develop a taste
     for good wine while over there.  I get to spend a week in Corsica
     unsupervised with a bunch of my cousin's friends, which basically
     means I'm hanging out with a bunch of french girls my age.  I
     hope they're cute, or good kissers, or at least interesting to
     talk to.
     
     I reconnected with Anneliese earlier this month, I think.  It was
     recent.  It felt good to be back on speaking terms with someone
     whom I liked so much.  She didn't change all that drastically,
     but she's been putting up with some apparently really rough home
     life stuff.  She's moving out this Saturday, though, I think.  I
     hope she does well!  She figured out that Grace was an asshole,
     too, but it was a little late.  Better late than never with
     things like that, though.  I still find myself a bit attracted to
     her, since she's capable of engaging me mentally and she has a
     good body, but nothing's ever happening there.  I think she set
     my standards a little on the high side for my next girlfriend,
     though.  Like, whoever I date next has to be a pretty solid
     conversationalist, since Anneliese was always able to keep
     talking if we wanted to.
     
     I guess I say girlfriend, but there's every chance in the world
     some cute boy will walk into my life and mess me up just the same
     way a girl could.  It's a little rarer for guys to do that to me,
     but it's happened before and the aftermath was interesting the
     last time it did.  I don't think I have time to tell the story of
     Danny here, though.  Just know I'm long over him but I really
     liked him a great deal for a couple years there.
     
     God, people are so attractive and if I don't stop writing here
     this will just devolve into the biggest lonely bisexual ramble of
     all time so I'm cutting this paragraph off right here.

     Speaking of lonely bisexuals, Dodie Clark came out as bi earlier
     this week!  Dodie has a nice voice and she's really adorable and
     I like the way she does her eyeliner.  I especially like her
     vlogs and her collabs with Andie Isalie [sp?].  Also she has a
     thing for tea and I connect with that on a spiritual level.

     This new laptop (the x230i, purchased ostensibly as a beater
     laptop for bringing to France) is so damn cute!  It's very small
     and has all the features I really like (good key travel, battery
     life, trackpoint, build quality) while actually being an
     ultraportable.  I swear businesspeople for the past couple
     decades haven't had nice jobs from my point of view, but they've
     always had the coolest laptops.  Thinkpads and latitudes have
     been way cooler than consumer stuff for a while now.  Only at
     this point have the consumer models started to catch up in
     general "coolness" and only the expensive ones that I wouldn't be
     willing to afford anyway.

     Anyway, yeah!  It's been a great few months.  I'll try to write
     tomorrow.

     Best Wishes,
     John Markiewicz
*** 2016-05-25 Wednesday
**** Entry.
     So, I suppose it's not "tomorrow," but it's close enough for
     government work, since it's only about ten minutes into Thursday.
     I keep playing guitar, lately.  It's really a great feeling,
     since somehow there's been an amazing musical drive shifted into
     play within me some time in the school year.  Speaking of the
     school year, at this point I never have to do any work for
     Watterson again.  It's just a couple bits of singing and I'm
     done.  That, in my eyes, is the best possible thing I could be
     able to say.  High school has made me who I am today, but I still
     vaguely resent it.

     Been listening to the track "Swim" by Fickle Friends lately.
     It's pretty poppy alt, a la The 1975, except FF are a bit better.
     Also a female lead vocalist.  I have a weakness for bands with
     alto vocalists because that's where it's the most fun to sing
     modern music.  Classical is different because I use a totally
     different set of techniques and often not even the same
     registers.  Music is weird.
     
     There's a lot to be glad about, though.  Life's pretty goddamn
     good.  Don't have to wake up at all until Saturday, and then only
     once.  Next time I wake up early I get paid for it.  Looking
     forward to France.  Enjoying this laptop, and the general feeling
     of life.  I have strong feelings in general right now, and
     lately.  Signed the wall downstairs today.  Never going back to
     the green room again.  Probably won't be back to Watterson before
     a show next happens, as far as after graduation is concerned.
     All the people I like, I can contact anyway.

     And besides, I'm going to be adding to the number of "people I
     like who I have access to" quite a bit over the next year.  The
     fact that I'll be surrounded not only by CSE majors but also by
     Music majors means I'll be having a lot of great people to deal
     with.  I think it's going to be my kind of gig.  I love music
     people and computer people.  I don't think most people would say
     those two specific groups, but I feel so distinctly at home with
     either group.  The same applies to theatre people.  Past those
     groups, it's not really the same.  I really enjoy the thought
     process of scientists and law people, though.  the
     straightforward approach has always been a favorite of mine.  You
     get that with Comp Sci people, though, and they like the same
     dorky shit I do.

     Palomino released the blackwing 24 recently.  I got a pack today,
     and they're pretty damn nice.  The gloss black toooootally works,
     and the lead is smooth yet keeps a point.  They're basically an
     idealized form of the #2.  I love it.  Then again, I'm kind of a
     sucker for blackwings, so it's no surprise I like their limited
     edition John Steinbeck pencil.  I need to read some Steinbeck
     yet.
     
     Anyway, that should do for now.  Take care, dear reader.
     
     Best Wishes,
     John Markiewiczz
*** 2016-05-27 Friday
**** Entry
     So, I'm back, bitch!

     Yeah, that's right, I've not died or anything similar to that.
     The journaling continues, and I think this time it's here to
     stay.  I don't know how much new shit I'll have to say each day
     during the off-months of the summer, since the real action
     happens right there in the middle when I leave the country.

     Shannon tried lisp today, and she really likes it.  Apparently
     macros and data structures just so happen to be her thing, and
     lisp goes right the fuck to that.  I like lisp, and I'm getting
     into the swing of writing lisp code.  It has this sort of really
     sensible syntax where all of it is the same sort of syntax.  It's
     all lists and atoms.  Emacs runs lisp all the way down, so I like
     that feature of it.
     
     [Journaling ended abruptly, continued in tomorrow's entry or
     something]

     Best Wishes,
     John Markiewicz
*** 2016-05-31 Tuesday
**** Entry
     Hey gang,
     
     Tried stealing an intro from Sav Brown.  Did it work?  No?  It
     was weird and vaguely cringey?  Ok.
     
     This marks a weird point in journaling.  I've never stuck out a
     journal this far, which is a combination of sad and just the fact
     I didn't have the investment or time to stick around before.  I'm
     putting the habit into place now, picking a time that's a lot
     more apt to have it stick than before.  The summer this year is a
     time for me of recovery, of learning, of reinvention (to a small
     degree) and of perspective.  The journaling works with that, and
     it counts as part of the learning/reinvention.
     
     Lisp is interesting to me, but I'm still not terribly far into
     it.  I understand just enough emacs lisp to be able to, say,
     write a macro to make org-mode more powerful for my use cases but
     not quite powerful enough to, say, write anything that stands on
     its own.  For that, I think I'd need something worth writing that
     wasn't already built in emacs, and my tablature idea kind of
     doesn't cut it since someone did that almost 20 years ago.
     
     Fuck, man, I was born almost 20 years ago.  That's a trip.
     
     Anyway, there's a lot of stuff I'm doing, or ought to be doing,
     or whatever.  I'm learning lisp (common) and perl (the only type
     of perl I'm aware of, perl) and also want to write and compose
     and perform and prepare and pick up some French and keep track of
     the Rocky Horror Picture Show and real stage shows while I'm at
     it.  Lots of things.
     
     Anyway, I'm liking this editor a lot more now.  It feels right
     for lisp development, and for noncode stuff, and for LaTeX, which
     basically means it's got me covered for the time being.  Emacs
     feels a little wrong, because I'm surrounded by vim people, but I
     still have my trusty vim keybindings.
     
     Anyway, I think I'll continue this later, if I have anything
     worthwhile to add.
     
     Best Wishes,
     John Markiewicz
** 2016-06 June
*** 2016-06-05 Sunday
**** Entry
     Aha!  Bet you thought I was gone, huh?  Nope!  I'm here for
     fucking ever.  Or at least, a while.  I'm not going to allow my
     first properly executed journal die that easily.
     
     I mean, I'm still writing this as of Monday, so it's a
     slower-written entry, but I started it late.  Cut me a break.  I
     tend not to be the most on-timey when it comes to the shit I do
     of my own accord, since it matters more to me and less to anyone
     else.  This being a special example, where it means something
     exclusively to me.  I guess that's part of why I don't often keep
     a journal.

     Maybe I should come up with a way to encrypt old entries, that
     would be an interesting script.  It wouldn't really serve much of
     a purpose, because anyone I'm liable to write about in this is
     unlikely to be someone able to use my laptop.  I guess that'll
     stop being as true as time passes, though.  I tend to take to
     people who like computers, so it's no doubt that eventually
     they'll be the majority of the people I feel strongly about.
     There are some great perks to tech people, since they tend to be
     a little more logical and a little less socially apt.
     
     Anyway, some other time.  Some other time.  Maybe later, maybe
     tomorrow, I'll write a proper entry, and you'll see.

     Best Wishes,
     John Markiewicz
*** 2016-06-08 Wednesday
**** Entry
     Yeah, yeah, it's a couple days later, but you know what?  I'm
     writing.  That counts for something, no?
     
     The feet and battery for this laptop have been in for a bit, and
     it's fantastic.  This is the nicest setup I've ever had for
     portable development/writing/browsing/etc.  I look forward,
     however, to the option of the Ben Nanonote.  Need to get a hold
     of Ida Systems on when that should arrive.
     
     Also, my emacs setup just keeps getting nicer.  It's a weird
     system, because in a program I have some weird C code base, with
     towering layers of elisp written overtop of it, and somehow this
     modern product (that is, a "modern" lisp machine with a not at
     all modern lisp implementation) comes out on the other side.  I
     can't help but think that a rewrite of my favorite features in
     something a little simpler (say, a compiled common lisp or
     something) would be way more solid, but I don't really understand
     how I'd go about rewriting the features of org-mode (or really,
     emacs) that I'd like to reimplement.  maybe a little more reading
     and understanding would do me some good, though knowing the
     general quality of GNU project code I'm not so sure.
     
     I want to write a musical.  I was thinking the way Eddie got into
     the pickle he ended up in by the Rocky Horror Picture Show, but
     then I thought that the licensing on that could become an
     enormous pain in the ass.  I don't have that kind of money, and I
     would want this musical to at least be performable.  I also want
     to put on a production of The Rocky Horror Picture Show itself,
     but that's going to be pretty tricky.
     
     I'm going to go, and try to write something unrelated.  

     Best Wishes,
     John Markiewicz
*** 2016-06-09 Thursday
**** Entry

